config/routes.rb
Rails.application.routes.draw do
  get 'messages/reply'

  resources :meetings
  resources :cakes
  resources :people
  resources :meetings

  root 'meetings#index'

  resource :messages do
    collection do
      post 'reply'
    end
  end

end

app/models/cake.rb
class Cake < ActiveRecord::Base
  has_many :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :cake
  belongs_to :person
  validates :cake_id, presence: true
  validates :person_id, presence: true
  validate :friday, on: [:create,:update]

  def friday
    errors.add(:date,"not is friday") unless date.friday?
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :meeting, dependent: :delete_all
  attr_encrypted :cellphone, key: Rails.application.secrets.secret_key_base
  validates :cellphone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  before_action :set_cake, only: [:show, :edit, :update, :destroy]

  # GET /cakes
  # GET /cakes.json
  def index
    @cakes = Cake.all
  end

  # GET /cakes/1
  # GET /cakes/1.json
  def show
  end

  # GET /cakes/new
  def new
    @cake = Cake.new
  end

  # GET /cakes/1/edit
  def edit
  end

  # POST /cakes
  # POST /cakes.json
  def create
    @cake = Cake.new(cake_params)

    respond_to do |format|
      if @cake.save
        format.html { redirect_to @cake, notice: 'Cake was successfully created.' }
        format.json { render :show, status: :created, location: @cake }
      else
        format.html { render :new }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cakes/1
  # PATCH/PUT /cakes/1.json
  def update
    respond_to do |format|
      if @cake.update(cake_params)
        format.html { redirect_to @cake, notice: 'Cake was successfully updated.' }
        format.json { render :show, status: :ok, location: @cake }
      else
        format.html { render :edit }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cakes/1
  # DELETE /cakes/1.json
  def destroy
    @cake.destroy
    respond_to do |format|
      format.html { redirect_to cakes_url, notice: 'Cake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cake
      @cake = Cake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cake_params
      params.require(:cake).permit(:name)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
      @meetings = Meeting.all.order('date DESC')
      fresh_when(@meetings)
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save

        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meeting_params
    params.require(:meeting).permit(:date, :cake_id, :person_id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    @person.cellphone=""
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:name, :cellphone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cakes/_form.html.erb
<%= form_for(@cake, html:{class:"form-horizontal"}) do |f| %>
  <% if @cake.errors.any? %>
    <div class="text-danger" id="error_explanation">
      <h2><%= pluralize(@cake.errors.count, "error") %> prohibited this cake from being saved:</h2>

      <ul class="bg-danger">
        <% @cake.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/cakes/edit.html.erb
<h1>Editing Cake</h1>

<%= render 'form' %>

<%= link_to 'Show', @cake, class:"btn btn-default" %> |
<%= link_to 'Back', cakes_path, class:"btn btn-default" %>

app/views/cakes/index.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<h1>Listing Cakes</h1>
<div class="row">
  <div class="col-sm-10">
    <%= link_to 'New Cake', new_cake_path, class:"btn btn-default " %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cakes.each do |cake| %>
        <tr>
          <td><%= cake.name %></td>
          <td><%= link_to 'Show', cake, class:"btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_cake_path(cake), class:"btn btn-default" %></td>
          <td><%= link_to 'Destroy', cake, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/cakes/new.html.erb
<h1>New Cake</h1>

<%= render 'form' %>

<%= link_to 'Back', cakes_path %>

app/views/cakes/show.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<p class="form-control-static">
  <strong>Name:</strong>
  <%= @cake.name %>
</p>

<%= link_to 'Edit', edit_cake_path(@cake), class:"btn btn-default" %> |
<%= link_to 'Back', cakes_path, class:"btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>

    <%= nav_bar static: :top, brand: "Bolo de sexta", responsive: true do %>
      <%= menu_group do %>
        <%= menu_item "Meetings", meetings_path %>
        <%= menu_item "Cakes", cakes_path %>
        <%= menu_item "People", people_path %>
      <% end %>
    <% end %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting, html:{class:"form-horizontal"}) do |f| %>
  <% if @meeting.errors.any? %>
    <div class="text-danger" id="error_explanation">
      <h2 ><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul class="bg-danger">
        <% @meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

    <div class="col-sm-10">
      <%= f.label :date %><br>
      <%= f.date_select :date, discard_year: true%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :cake_id %><br>
      <%= f.collection_select(:cake_id, Cake.order(:name),:id, :name,:prompt => true) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :person_id %><br>
      <%= f.collection_select(:person_id,Person.order(:name),:id, :name,:prompt => true)%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting, class:"btn btn-default" %> |
<%= link_to 'Back', meetings_path, class:"btn btn-default" %>

app/views/meetings/index.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>
<div class="row">
  <div class="col-sm-10 text-right">
    <%= link_to 'New Meeting', new_meeting_path, class:"btn btn-success" %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Cake</th>
        <th>Person</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @meetings.each do |meeting| %>
        <% cache meeting do %>
        <tr>
        <td><%= meeting.date %></td>
        <td><%= meeting.cake.name %></td>
        <td><%= meeting.person.name %></td>
        <td><%= link_to 'Show', meeting, class:"btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting),class:"btn btn-default" %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" %></td>
      </tr>
    <% end %>
    <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path, class:"btn btn-default" %>

app/views/meetings/show.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<p class="form-control-static">
  <strong>Date:</strong>
  <%= @meeting.date %>
</p>

<p class="form-control-static">
  <strong>Cake:</strong>
  <%= @meeting.cake.name %>
</p>

<p class="form-control-static">
  <strong>Person:</strong>
  <%= @meeting.person.name %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting), class:"btn btn-default" %> |
<%= link_to 'Back', meetings_path, class:"btn btn-default" %>

app/views/people/_form.html.erb
<%= form_for(@person, html:{class:"form-horizontal"}) do |f| %>
  <% if @person.errors.any? %>
    <div class="text-danger" id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul class="bg-danger">
        <% @person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-10">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="col-sm-10">
      <%= f.label :cellphone %><br>
      <%= f.telephone_field :cellphone %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person, class:"btn btn-default" %> |
<%= link_to 'Back', people_path, class:"btn btn-default" %>

app/views/people/index.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<h1>Listing People</h1>
<div class="row">
  <div class="col-sm-10">
    <%= link_to 'New Person', new_person_path, class:"btn btn-default" %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.name %></td>
          <td><%= link_to 'Show', person, class:"btn btn-default"  %></td>
          <td><%= link_to 'Edit', edit_person_path(person), class:"btn btn-default"  %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p class="bg-success" id="notice"><%= notice %></p>

<p class="form-control-static">
  <strong>Name:</strong>
  <%= @person.name %>
</p>
<p class="form-control-static">
  <strong>Phone Number:</strong>
  <%= number_to_phone @person.cellphone, country_code:55%>
</p>
<p class="form-control-static">
  <strong>The phone number is encrypted</strong>
</p>

<%= link_to 'Edit', edit_person_path(@person), class:"btn btn-default" %> |
<%= link_to 'Back', people_path, class:"btn btn-default" %>